import { Model } from "..";

export enum PROFILE_GETTERS {
  CURRENT_PROFILE = 'GET_CURRENT_PROFILE',
}

export enum PROFILE_REDUCERS {
  SET_INDEX_PROFILE = 'REDUCER:SET_INDEX_PROFILE',
  SET_PROFILES = 'REDUCER:SET_PROFILES',
  ADD_PROFILE = 'REDUCER:ADD_PROFILE'
}

export enum PROFILE_EFFECTS {
  ADD_PROFILE = 'addProfile',
}

export enum PROFILE_ACTIONS {
  SET_INDEX_PROFILE = `${Model.PROFILE}/${PROFILE_REDUCERS.SET_INDEX_PROFILE}`,
  SET_PROFILES = `${Model.PROFILE}/${PROFILE_REDUCERS.SET_PROFILES}`,
  REDUCER_ADD_PROFILE = `${Model.PROFILE}/${PROFILE_REDUCERS.ADD_PROFILE}`,
  ADD_PROFILE = `${Model.PROFILE}/${PROFILE_EFFECTS.ADD_PROFILE}`
}